JCC = javac

default: Tokenizer.class Assign.class  Dig.class  Fac.class  In.class Let.class Prog.class Comp.class DL.class Id.class   InputReader.class  Loop.class  SS.class CompO.class   DS.class   IDL.class Interpreter.class  Op.class    ST.class	Cond.class    Exp.class  If.class   Int.class Out.class   Tokenizer.class


Tokenizer.class: Tokenizer.java
	$(JCC) Tokenizer.java

Tokenize.class: Tokenize.java
	$(JCC) Tokenize.java	
	
Assign.class: Assign.java
	$(JCC) Assign.java
  
Dig.class: Dig.java
	$(JCC) Dig.java
	
Fac.class: Fac.java  
	$(JCC) Fac.java

In.class: In.java
	$(JCC) In.java           

Let.class: Let.java
	$(JCC) Let.java   

Prog.class: Prog.java
	$(JCC) Prog.java

Comp.class: Comp.java
	$(JCC) Comp.java 
   
DL.class: DL.java
	$(JCC) DL.java
   
Id.class: Id.java
	$(JCC) Id.java  
 
InputReader.class: InputReader.java
	$(JCC) InputReader.java  

Loop.class: Loop.java
	$(JCC) Loop.java  

SS.class: SS.java
	$(JCC) SS.java

Comp0.class: Comp0.java
	$(JCC) CompO.java  

DS.class: DS.java
	$(JCC) DS.java   

IDL.class: IDL.java
	$(JCC) IDL.java  

Interpreter.class: Interpreter.java
	$(JCC) Interpreter.java  

Op.class: Op.java
	$(JCC) Op.java   
 
ST.class: ST.java
	$(JCC) ST.java

Comd.class: Cond.java
	$(JCC)Cond.java  
  
Exp.class: Exp.java
	$(JCC) Exp.java  

If.class: If.java
	$(JCC) If.java  
 
Int.class: Int.java
	$(JCC) Int.java  
        
Out.class: Out.java
	$(JCC) Out.java
	
clean: 
	$(RM) *.class
